TFW: Added action to check for copyright in Yoko src files

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -23,6 +23,21 @@ jobs:
         distribution: 'adopt'
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
+    - name: Check for copyright in yoko source files
+      run: |
+        SRC=$(find yoko*/ -name '*.java')
+        CopyrightText="http://www.apache.org/licenses/LICENSE-2.0"
+        RC=0
+        echo "Checking copyright in Yoko src files"
+        for filePath in $SRC; do
+          if grep -q "$CopyrightText" $filePath; then
+              echo "✅ Copyright OK: $filePath"
+          else
+              echo "❌ Copyright not found in $filePath"
+              RC=1
+          fi
+        done
+        exit $RC
     - name: Check copyright Tag in Testify source files
       run: |
         SRC=$(find testify/ -name '*.java')
